function [f,dd] = fgrade(FM,x,k)
% FGRADE calculate membership degree in multidimensional fuzzy sets.
% [F,F1] = FGRADE(FM,X) calculates membership grades of the elements of
% X into clusters (multi-dimensional fuzzy sets) defined in FM
% which is generated by FMCLUST. 
%
% F is computed by using the clustering-like formula (probabilistic)
% and F1 is computed by the similarity-like formula (possibilistic).

% (c) Robert Babuska, 1994-98

c = FM.c(k);
m = FM.m(k);
M = FM.M{k};
NI = size(FM.rls{k},2);

x1 = ones(size(x,1),1);
d = [];
for j = 1 : c, 				% for all clusters
   xv = x - x1*FM.V{k}(j,:);
   d(:,j) = sum(xv*M(:,:,j).*xv,2);
end;
dd = 1./(1+d);
d = (d+1e-100).^(-1/(m-1));          % clustering dist
f = (d ./ (sum(d')'*ones(1,c)));
